logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    com.example.airbnbcloneback: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: home-booking-app-back
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
    url: jdbc:postgresql://localhost:5432/airbnb-clone
    username: postgres
    password: 8ecdjo5tg
    driver-class-name: org.postgresql.Driver
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: airbnb_clone
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: airbnb_clone
    enabled: true
  #    drop-first: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8080

okta:
  oauth2:
    issuer: https://dev-bcfgvuktrh512py2.us.auth0.com/
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}

application:
  auth0:
    role-landlord-id: rol_QZ4S2qmLdQ8DJ0Hw
